export const enum QueryKeys {
  CreateBook = 'createBook',
  GetAllBooks = 'getAllBooks',
  GetBookById = 'getBookById',
  DeleteBook = 'deleteBook',
  UpdateBook = 'updateBook',
  SearchBooks = 'searchBooks',
  CreateAuthor = 'createAuthor',
  GetAllAuthors = 'getAllAuthors',
  GetAuthorById = 'getAuthorById',
  UpdateAuthor = 'updateAuthor',
  DeleteAuthor = 'deleteAuthor',
  CreateLibrary = 'createLibrary',
  GetAllLibrarys = 'getAllLibrarys',
  GetLibraryById = 'getLibraryById',
  DeleteLibrary = 'deleteLibrary',
  UpdateLibrary = 'updateLibrary',
  CreateGenre = 'createGenre',
  GetAllGenres = 'getAllGenres',
  GetGenreById = 'getGenreById',
  DeleteGenre = 'deleteGenre',
  UpdateGenre = 'updateGenre',
  Login = 'login',
  Register = 'register',
}
